name: BlobMenu
version: ${project.version}
main: io.github.anjoismysign.blobmenu.BlobMenu
api-version: ${minecraft.version}
load: POSTWORLD
depend:
  - BlobLib
authors: [ anjoismysign ]
commands:
  blobmenu:
    description: info blobmenu